config:
- &docker-config
  insecure_registries: ["10.0.2.2:6000"]


resources:
- name: every-1m
  type: time
  source: {interval: 5m}

- name: yslow-image
  type: docker-image
  source:
     <<: *docker-config
     repository: "10.0.2.2:6000/yslow-image"


jobs:
- name: yslow
  plan:
  - get: every-1m
    trigger: true
  - task: score
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: yslow-image}
      run:
        path: yslow.sh

