config:

- &git-config
  uri: git@github.com:dekka75/yslow.git
  branch: master
  private_key: {{ci-ssh-key}}

- &docker-config
  insecure_registries: ["10.0.2.2:6000"]

resources:

- name: yslow-image-repo
  type: git
  source:
    <<: *git-config
    paths: [ci/dockerfiles/yslow-dockerfile]

- name: yslow-image
  type: docker-image
  source:
    <<: *docker-config
    repository: "10.0.2.2:6000/yslow-image"

jobs:

- name: build-yslow-image
  plan:
  - get: yslow-image-repo
    trigger: true
  - put: yslow-image
    params:
      build: yslow-image-repo
      dockerfile: yslow-image-repo/ci/dockerfiles/yslow-dockerfile

- name: yslow
  plan:
  - task: score
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: yslow-image}
      run:

